Repository marmelab/kuba-integration, pull requests merged in 2021-09, with the labels that each got.

#11 I want to know when a player has won
  assets/board-test.json
  assets/board.json
  src/board.spec.ts
  src/board.ts
  src/game.spec.ts
  src/game.ts
  src/graph.spec.ts
  src/graph.ts
  src/renderBoard.ts
  src/types.ts
Labels: Work In Progress, Not to merge

#17 Deploy API on EC2
  Makefile
  api/package.json
  api/yarn.lock
  client/.env
  client/package.json
  client/src/constants.ts
  client/src/index.ts
  client/yarn.lock
Labels: Work In Progress

#26 Add Yarn Workspace
  admin/.gitignore
  admin/README.md
  admin/package.json
  admin/public/favicon.ico
  admin/public/index.html
  admin/public/logo192.png
  admin/public/logo512.png
  admin/public/manifest.json
  admin/public/robots.txt
  admin/src/App.tsx
  admin/src/User/index.tsx
  admin/src/dataProvider.tsx
  admin/src/index.css
  admin/src/index.tsx
  admin/src/react-app-env.d.ts
  admin/src/reportWebVitals.ts
  admin/tsconfig.json
  api/package.json
  api/prisma/migrations/20210913094224_init/migration.sql
  api/prisma/schema.prisma
  api/src/app.controller.spec.ts
  api/src/app.controller.ts
  api/src/app.gateway.ts
  api/src/app.module.ts
  api/src/app.service.ts
  api/src/board.ts
  api/src/game.service.ts
  api/src/game.spec.ts
  api/src/game.ts
  api/src/game/game.controller.ts
  api/src/game/game.module.ts
  api/src/game/game.service.ts
  api/src/graph.spec.ts
  api/src/graph.ts
  api/src/main.ts
  api/src/prisma.service.ts
  api/src/user/user.controller.ts
  api/src/user/user.module.ts
  api/src/user/user.service.ts
  api/yarn.lock
  client/package-lock.json
  client/package.json
  client/src/api.spec.ts
  client/src/api.ts
  client/src/userInput.ts
  client/yarn.lock
  package.json
  yarn.lock
Labels: RFR

#24 api clean :
  api/src/app.controller.ts
  api/src/app.gateway.ts
  api/src/app.module.ts
  api/src/app.service.ts
  api/src/error.ts
  api/src/game/game.controller.ts
  api/src/game/game.module.ts
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.module.ts
  api/src/gameState/gameState.service.ts
  client/src/api.ts
  client/src/blessed.ts
  client/src/error.ts
  client/src/index.ts
Labels: RFR

#28 Orchestrate with docker
  admin/cypress.json
  admin/cypress/fixtures/example.json
  admin/cypress/integration/kuba_admin_spec.js
  admin/cypress/plugins/index.js
  admin/cypress/support/commands.js
  admin/cypress/support/index.js
  admin/package.json
  api/docker/postgres/docker-compose.yml
  docker-compose.yml
  yarn.lock
Labels: RFR

#27 Add end to end test on User Crud with Cypress.
  admin/cypress/integration/kuba_admin_spec.js
  admin/cypress/support/commands.js
  admin/package.json
  yarn.lock
Labels: RFR

#22 Api auth
  .gitignore
  admin/src/index.tsx
  admin/tsconfig.json
  api/.gitignore
  api/package-lock.json
  api/package.json
  api/prisma/migrations/20210913094224_init/migration.sql
  api/prisma/migrations/20210915085327_init/migration.sql
  api/prisma/schema.prisma
  api/src/app.module.ts
  api/src/auth/auth.controller.ts
  api/src/auth/auth.module.ts
  api/src/auth/auth.service.spec.ts
  api/src/auth/auth.service.ts
  api/src/auth/constants.ts
  api/src/auth/jwt-auth.guard.ts
  api/src/auth/jwt.strategy.ts
  api/src/auth/local-auth.guard.ts
  api/src/auth/local.strategy.ts
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.module.ts
  api/src/user/user.controller.ts
  api/src/user/user.module.ts
  api/src/user/user.service.ts
  api/tsconfig.json
  client/src/api.ts
  client/src/blessed.ts
  client/src/index.ts
  client/tsconfig.json
  yarn.lock
Labels: RFR

#29 Add allowed header on nest
  api/src/main.ts
Labels: RFR

#30 Admin game
  admin/src/App.tsx
  admin/src/Game/Board.tsx
  admin/src/Game/List.tsx
  admin/src/Game/Show.tsx
  admin/src/Game/User.tsx
  admin/src/dataProvider.tsx
  api/src/admins/admins.controller.ts
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.service.ts
  api/src/main.ts
  api/src/user/user.controller.ts
  client/src/api.ts
  client/src/blessed.ts
  client/src/index.ts
  docker-compose.yml
Labels: RFR

#32 Admins tests
  admin/cypress/integration/kuba_admin_spec.js
  admin/cypress/integration/kuba_admins_spec.js
  admin/cypress/integration/kuba_auth_spec.js
  api/src/admins/admins.controller.ts
Labels: RFR

#33 Delete game and filter game
  admin/src/App.tsx
  admin/src/Game/Show.tsx
  admin/src/User/index.tsx
  admin/src/dataProvider.tsx
  api/src/custom.pipe.ts
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.service.ts
  api/src/user/user.controller.ts
  api/src/user/user.service.ts
Labels: RFR

#34 Adding a player's game list
  admin/src/Admins/index.tsx
  admin/src/App.tsx
  admin/src/Game/List.tsx
  admin/src/User/index.tsx
  admin/src/dataProvider.tsx
  api/prisma/migrations/20210919014412_init/migration.sql
  api/prisma/schema.prisma
  api/src/custom.pipe.ts
  api/src/gameState/gameState.controller.ts
  api/src/user/user.controller.ts
  api/src/user/user.service.ts
Labels: RFR

#35 Username dates addition
  admin/src/Game/List.tsx
  admin/src/User/index.tsx
  api/prisma/migrations/20210916075731_init/migration.sql
  api/prisma/migrations/20210919014412_init/migration.sql
  api/prisma/migrations/20210921145142_init/migration.sql
  api/prisma/schema.prisma
  api/src/auth/auth.controller.ts
  api/src/auth/auth.service.ts
  api/src/gameState/gameState.service.ts
  api/src/types.ts
  api/src/user/user.controller.ts
  api/src/user/user.service.ts
Labels: RFR

#36 Add id filter for user
  api/src/custom.pipe.ts
Labels: RFR

#37 Return board with gameState
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.service.ts
  api/src/types.ts
Labels: RFR

#38 Add event notification
  api/prisma/schema.prisma
  api/src/admins/admins.controller.ts
  api/src/app.gateway.ts
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.service.ts
  api/src/user/user.controller.ts
  client/src/api.ts
Labels: RFR

#40 Return graph with Get game
  api/src/gameState/gameState.controller.ts
Labels: RFR

#41 Send marbles to animate via WebSocket.
  api/src/gameState/gameState.service.ts
Labels: RFR

#39 Api changes
  Readme.md
  api/prisma/migrations/20210929202716_init/migration.sql
  api/prisma/schema.prisma
  api/src/auth/auth.module.ts
  api/src/custom.pipe.ts
  api/src/gameState/gameState.controller.ts
  api/src/gameState/gameState.service.ts
  api/src/types.ts
  client/src/types.ts
Labels: RFR

#42 Fix playerId scories
  api/src/gameState/gameState.service.ts
Labels: RFR
